name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.

  - type: input
    id: version
    attributes:
      label: DDEV Manager version
      description: "Find this in Settings or Help > About"
      placeholder: "e.g., 0.5.1"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS version
      placeholder: "e.g., macOS 14.0, Windows 11, Ubuntu 22.04"

  - type: input
    id: ddev-version
    attributes:
      label: DDEV version
      description: "Run `ddev version` in terminal"
      placeholder: "e.g., v1.23.0"

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context about the problem (logs, error messages, etc.)
